.onAttach <- function(...) {
  if(requireNamespace("gagglr", quietly = TRUE))
    gagglr::oha_check("gophr", suppress_success = TRUE)
}


utils::globalVariables(
  c(".",
    ":=",
    "achievement",
    "achievement_qtrly",
    "achv_value",
    "action",
    "age_2018",
    "age_2019",
    "agecoarse",
    "agefine",
    "agency",
    "agesemifine",
    "apr",
    "caption",
    "code",
    "cop_budget_pipeline",
    "country",
    "countryname",
    "cumulative",
    "datim_status",
    "description",
    "Description of the issue",
    "Email Address",
    "entry_close",
    "exclude_cop_budget_total",
    "exclude_targets",
    "fiscal_year",
    "fiscal_year_label",
    "funding_agency",
    "funding_agency_zXz",
    "fundingagency",
    "fy",
    "How should the data issue be handled?",
    "implementation_year",
    "implementingmechanismname",
    "indicator",
    "indicatortype",
    "interaction_type",
    "Is there a specific quarter affected?",
    "Is there an OPU open/pending at this time?",
    "key",
    "key_date",
    "Mech ID",
    "mech_code",
    "mech_id",
    "mech_name",
    "mech_name_zXz",
    "mechanism",
    "Mechanism ID",
    "mechanismid",
    "mechanismuid",
    "moh-secondment",
    "msd_release",
    "partner",
    "Partner Type",
    "partner_type_usaid",
    "period",
    "period_type",
    "POC",
    "prime_partner_name",
    "prime_partner_name_zXz",
    "primepartner",
    "qtr",
    "qtr_goal",
    "qtr1",
    "qtr4",
    "quarter",
    "record_type",
    "resolved",
    "resolved?",
    "results",
    "results_cumulative",
    "resultstatus",
    "snapshot_ind",
    "standardizeddisaggregate",
    "targets",
    "Timestamp",
    "trendsfine",
    "trendssemifine",
    "value",
    "What fiscal year has this issue?",
    "What indicators are affected?",
    "What is the preferred mechanism name?",
    "What is the specific mechanism id?",
    "What PEPFAR country is affected?",
    "where",
    "Where does the known issue reside?",
    "x")
  )
